# Admin / Pipeline Consumer & API Service
user dale_admin
topic readwrite hospital/#
topic readwrite hospital/devices/#

# Simulator Device Client / Dispatcher
user wms_device
topic readwrite hospital/devices/#

# General pattern
pattern readwrite hospital/devices/%u/#
